[package]
name = "http1_by_hand"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.4"
nom = "8.0.0"
rustls = "0.23.27"
rustls-native-certs = "0.8.1"
tokio = { version = "1.45.1", features = ["full"] }
tokio-rustls = "0.26.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
